# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: bash -c "cd ./todo_project && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/todo_project
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
